"""Shared typography settings for figures generated by ``src.items``."""

from __future__ import annotations

import matplotlib.pyplot as plt


def configure_plot_style() -> None:
    """Use a Times-compatible serif face and consistent enlarged text."""
    plt.rcParams.update({
        # Times New Roman is preferred; Nimbus Roman is its installed substitute.
        "font.family": "serif",
        "font.serif": ["Times New Roman", "Nimbus Roman", "Times"],
        "mathtext.fontset": "stix",
        "font.size": 14,
        "axes.labelsize": 16,
        "axes.titlesize": 16,
        "xtick.labelsize": 13,
        "ytick.labelsize": 13,
        "legend.fontsize": 13,
        "figure.titlesize": 16,
    })
